version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kms-sys-app
    container_name: kms-sys-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - kms-sys-network

  db:
    image: mysql:8.0.32
    platform: linux/amd64
    container_name: kms-sys-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kms-sys-network

  nginx:
    image: nginx:1.23.3
    platform: linux/amd64
    container_name: kms-sys-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - kms-sys-network
    depends_on:
      - app

networks:
  kms-sys-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
